// src/app/components/contact-form/contact-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import emailjs from '@emailjs/browser';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-contact-form',
  templateUrl: './contact-form.component.html'
})
export class ContactFormComponent {
  contactForm: FormGroup;
  isSubmitting = false;

  constructor(
    private fb: FormBuilder,
    private toastr: ToastrService
  ) {
    this.contactForm = this.fb.group({
      user_name: ['', Validators.required],
      user_email: ['', [Validators.required, Validators.email]],
      message: ['', Validators.required]
    });
  }

  async onSubmit() {
    if (this.contactForm.invalid) return;

    this.isSubmitting = true;

    try {
      const result = await emailjs.send(
        'service_dp6q9iv',
        'template_g0v8zbs',
        this.contactForm.value,
        '5xHzaRnQcqSqDQB-T'
      );

      console.log('Email sent successfully:', result.text);
      this.toastr.success('Το μήνυμά σας στάλθηκε με επιτυχία!');
      this.contactForm.reset();
    } catch (error: any) {
      console.error('Failed to send email:', error.text);
      this.toastr.error('Υπήρξε ένα πρόβλημα. Παρακαλώ δοκιμάστε ξανά.');
    } finally {
      this.isSubmitting = false;
    }
  }
}
<div class="bg-white p-8 rounded-lg shadow-md">
  <h3 class="text-xl font-semibold mb-6">Στείλτε μου μήνυμα</h3>
  <form [formGroup]="contactForm" (ngSubmit)="onSubmit()" class="space-y-6">
    <div>
      <label for="user_name" class="block text-sm font-medium text-gray-700 mb-1">
        Ονοματεπώνυμο
      </label>
      <input
        type="text"
        id="user_name"
        formControlName="user_name"
        class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
        [class.border-red-500]="contactForm.get('user_name')?.invalid && contactForm.get('user_name')?.touched"
      />
    </div>
    <div>
      <label for="user_email" class="block text-sm font-medium text-gray-700 mb-1">
        Email
      </label>
      <input
        type="email"
        id="user_email"
        formControlName="user_email"
        class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
        [class.border-red-500]="contactForm.get('user_email')?.invalid && contactForm.get('user_email')?.touched"
      />
    </div>
    <div>
      <label for="message" class="block text-sm font-medium text-gray-700 mb-1">
        Μήνυμα
      </label>
      <textarea
        id="message"
        formControlName="message"
        rows="4"
        class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
        [class.border-red-500]="contactForm.get('message')?.invalid && contactForm.get('message')?.touched"
      ></textarea>
    </div>
    <button 
      type="submit" 
      [disabled]="contactForm.invalid || isSubmitting"
      class="w-full btn-primary disabled:opacity-70 disabled:cursor-not-allowed"
    >
      {{ isSubmitting ? 'Αποστολή...' : 'Αποστολή Μηνύματος' }}
      <i-lucide name="send" class="ml-2 h-4 w-4"></i-lucide>
    </button>
  </form>
</div>

// src/components/ContactForm.tsx
import React, { useState, useRef, FormEvent } from 'react';
import { Send } from 'lucide-react';
import emailjs from '@emailjs/browser';
import { toast } from 'react-hot-toast';
// στη φόρμα:
import ReCAPTCHA from 'react-google-recaptcha';

export const ContactForm: React.FC = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [captchaValue, setCaptchaValue] = useState<string | null>(null);
  const formRef = useRef<HTMLFormElement>(null);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    if (!captchaValue) {
      toast.error('Παρακαλώ επαληθεύστε ότι δεν είστε ρομπότ.');
      return;
    }
    
    if (!formRef.current) return;
    
    setIsSubmitting(true);
    
    emailjs.sendForm(
      'service_dp6q9iv', 
      'template_g0v8zbs', 
      formRef.current,
      '5xHzaRnQcqSqDQB-T'
    )
      .then((result) => {
        console.log('Email sent successfully:', result.text);
        toast.success('Το μήνυμά σας στάλθηκε με επιτυχία!');
        formRef.current?.reset();
      })
      .catch((error) => {
        console.error('Failed to send email:', error.text);
        toast.error('Υπήρξε ένα πρόβλημα. Παρακαλώ δοκιμάστε ξανά.');
      })
      .finally(() => {
        setIsSubmitting(false);
      });
  };

  return (
    <div className="bg-white p-8 rounded-lg shadow-md">
      <h3 className="text-xl font-semibold mb-6">Στείλτε μου μήνυμα</h3>
      <form ref={formRef} onSubmit={handleSubmit} className="space-y-6">
        <div>
          <label htmlFor="user_name" className="block text-sm font-medium text-gray-700 mb-1">
            Ονοματεπώνυμο
          </label>
          <input
            type="text"
            id="user_name"
            name="user_name"
            required
            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
          />
        </div>
        <div>
          <label htmlFor="user_email" className="block text-sm font-medium text-gray-700 mb-1">
            Email
          </label>
          <input
            type="email"
            id="user_email"
            name="user_email"
            required
            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
          />
        </div>
        <div>
          <label htmlFor="message" className="block text-sm font-medium text-gray-700 mb-1">
            Μήνυμα
          </label>
          <textarea
            id="message"
            name="message"
            rows={4}
            required
            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors"
          ></textarea>
        </div>
        <ReCAPTCHA
          sitekey="your_recaptcha_site_key_here"
          onChange={(value) => setCaptchaValue(value)}
        />
        <button 
          type="submit" 
          disabled={isSubmitting}
          className="w-full btn-primary disabled:opacity-70 disabled:cursor-not-allowed"
        >
          {isSubmitting ? 'Αποστολή...' : 'Αποστολή Μηνύματος'}
          <Send className="ml-2 h-4 w-4" />
        </button>
      </form>
    </div>
  );
};
